import { StyleSheet } from "react-native";

export const teacherColors = {
  background: "#fbfaf9",
  card: "#ffffff",
  text: "#202124",
  muted: "#555b66",
  border: "#c5cede",
  blue: "#0057d9",
  navy: "#274779",
  green: "#16a34a",
  orange: "#c84b16",
};

export const teacherStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: teacherColors.background },
  root: { flex: 1, backgroundColor: teacherColors.background },
  header: {
    minHeight: 63,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomColor: "#e1e4ea",
    borderBottomWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  logo: { color: teacherColors.blue, fontSize: 22, fontWeight: "900", lineHeight: 27 },
  headerSubtitle: { color: teacherColors.muted, fontSize: 13 },
  headerAction: { color: teacherColors.navy, fontSize: 13, fontWeight: "900" },
  scroll: { flex: 1 },
  content: { paddingHorizontal: 16, paddingTop: 18, paddingBottom: 28 },
  titleBlock: { marginBottom: 18 },
  title: { color: teacherColors.text, fontSize: 26, fontWeight: "900", lineHeight: 33 },
  subtitle: { marginTop: 6, color: teacherColors.muted, fontSize: 15, lineHeight: 21 },

  card: {
    borderRadius: 10,
    borderColor: teacherColors.border,
    borderWidth: 1,
    backgroundColor: teacherColors.card,
    padding: 16,
  },
  cardTitle: { color: teacherColors.text, fontSize: 18, fontWeight: "900", lineHeight: 24 },
  cardMeta: { marginTop: 6, color: teacherColors.muted, fontSize: 14, lineHeight: 20 },
  list: { gap: 12, marginTop: 16 },

  fieldLabel: {
    marginTop: 14,
    color: teacherColors.muted,
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.3,
  },
  input: {
    marginTop: 10,
    minHeight: 44,
    borderRadius: 8,
    borderColor: teacherColors.border,
    borderWidth: 1,
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: teacherColors.text,
    fontSize: 15,
  },
  textArea: { minHeight: 120, textAlignVertical: "top" },

  primaryButton: {
    minHeight: 42,
    borderRadius: 8,
    backgroundColor: teacherColors.navy,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  primaryButtonText: { color: "#ffffff", fontSize: 14, fontWeight: "900" },
  ghostAction: { color: teacherColors.muted, fontSize: 14, fontWeight: "800" },
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 46,
    borderRadius: 10,
    borderColor: teacherColors.border,
    borderWidth: 1,
    borderStyle: "dashed",
    backgroundColor: "#ffffff",
  },
  addButtonText: { color: teacherColors.navy, fontSize: 15, fontWeight: "900" },

  emptyText: {
    marginTop: 18,
    color: teacherColors.muted,
    fontSize: 15,
    lineHeight: 21,
    textAlign: "center",
  },
  errorText: { marginTop: 12, color: "#c31717", fontSize: 14, lineHeight: 20 },
  pressed: { opacity: 0.76 },
  disabled: { opacity: 0.48 },
});
